spring.application.name=online-bookstore
server.port=8080
spring.profiles.active=h2
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false